# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-02-14 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_gender_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='data_consent',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='sponsor_consent',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
