# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-02-15 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_sponsor_consent'),
        ('applications', '0016_auto_20190214_2121'),
    ]

    operations = [
    ]
