# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-02-19 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_merge_20190218_1144'),
        ('applications', '0017_merge_20190215_1336'),
    ]

    operations = [
    ]
